[theme]
base = "light"
primaryColor = "#16813D"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F5F7"
textColor = "#191D21"
linkColor = "#137337"
borderColor = "#E1E5E8"
greenColor = "#16813D"
greenBackgroundColor = "#EAF6ED"
greenTextColor = "#146C34"
dataframeHeaderBackgroundColor = "#F4F5F7"
showWidgetBorder = true
showSidebarBorder = true
baseRadius = "0.8rem"
buttonRadius = "0.6rem"
font = "sans-serif"
headingFont = "sans-serif"
codeFont = "monospace"
baseFontSize = 15

[theme.sidebar]
backgroundColor = "#F4F5F7"
secondaryBackgroundColor = "#FFFFFF"
borderColor = "#E1E5E8"
